#!/bin/sh
if [ "${SKIP_HOOKS:-0}" -gt 0 ] 2>/dev/null; then
    echo "[POST-MERGE] skipping hooks ($SKIP_HOOKS)"
    exit 0
fi

echo "[POST-MERGE] 📦 Checking for changes to dependencies"
IFS=$'\n'
PACKAGE_LOCK_REGEX="(^package-lock\.json)"
PACKAGES=$(git diff --name-only HEAD^1 HEAD | grep -E $PACKAGE_LOCK_REGEX || true)

if [ -n "$PACKAGES" ]; then
    for package in $PACKAGES; do
        echo "📦 $package was changed."
    done
    echo "📦 Running npm install to update your dependencies..."
    npm install --no-workspaces
    npm run lint:fix
else
    echo "📦 All packages up-to-date. No need to run npm install."
fi
